#@TYPE: Machine
#@NAME: Caisteal i.MX6UL Secure System
#@SOC: i.MX6UL
#@DESCRIPTION: Machine configuration for Caisteal i.MX6UL Secure System
#@MAINTAINER: Harkirat Singh Virk <harkiratsvirk@gmail.com>

MACHINEOVERRIDES =. "mx6:mx6ul:"

include conf/machine/include/imx-base.inc
include conf/machine/include/tune-cortexa7.inc

MACHINE_FEATURES += " pci wifi bluetooth"

KERNEL_DEVICETREE = "imx6ul-caisteal.dtb"
KERNEL_DEVICETREE_use-mainline-bsp = "imx6ul-caisteal.dtb"

PREFERRED_PROVIDER_u-boot = "u-boot-caisteal"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-caisteal"
#PREFERRED_PROVIDER_virtual/u-boot_mx6 = "u-boot-caisteal"
PREFERRED_PROVIDER_virtual/kernel_mx6 = "linux-caisteal"
PREFERRED_VERSION_linux-caisteal ?= "4.9"
 
# Use fslc u-boot by default. See also imx-base.inc.
UBOOT_MAKE_TARGET = ""
UBOOT_SUFFIX = "img"
SPL_BINARY = "SPL"
WKS_FILE = "imx-uboot-spl-bootpart.wks.in"

UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "mx6caisteal_config,sdcard"
UBOOT_CONFIG[emmc] = "mx6caisteal_config,sdcard"
UBOOT_CONFIG[qspi1] = "mx6caisteal_qspi1_config"
UBOOT_CONFIG[mfgtool] = "mx6caisteal_config"
